# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Deploy application to digitalocean
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.MW_DO_HOST }}
          username: ${{ secrets.MW_DO_USERNAME }}
          password: ${{ secrets.MW_DO_PASSWORD }}
          script: |
            cd /var/www/triplechoice.mediusware.xyz
            pwd
            git pull origin master
            source venv/bin/activate
            pip install -r requirements.txt
            python src/manage.py migrate
            deactivate
            npm install && npm run build
            rm -rf node_moduels
            rm -rf package.lock
            service apache2 reload
            
